-- Create the infrastructure
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS EV_RESEARCH;
-- CREATE SCHEMA IF NOT EXISTS EV_RESEARCH.RAW;
CREATE SCHEMA IF NOT EXISTS EV_RESEARCH.PUBLIC;
USE WAREHOUSE COMPUTE_WH;
